'use client';
import { useMemo, useState } from 'react';
type Item={id:string;title:string;description?:string;priceCents?:number;available:boolean};
type Category={id:string;name:string;items:Item[]};
type Area={id:string;name:string;feeCents:number};
type Delivery={pickupEnabled:boolean;paymentMethods:string[];areas:Area[];minimumOrderCents:number};
function brl(cents:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100)}
export default function DeliveryClient({slug,snapshot,delivery}:{slug:string;snapshot:any;delivery:Delivery}){
  const categories=(snapshot.categories??[])as Category[];
  const[cart,setCart]=useState<Record<string,{quantity:number;note:string}>>({});
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const[fulfillment,setFulfillment]=useState<'PICKUP'|'DELIVERY'>(delivery.pickupEnabled?'PICKUP':'DELIVERY');
  const[areaId,setAreaId]=useState('');
  const[submissionKey]=useState(()=>crypto.randomUUID());
  const items=useMemo(()=>categories.flatMap(c=>c.items),[categories]);
  const subtotal=useMemo(()=>items.reduce((sum,item)=>sum+(item.priceCents??0)*(cart[item.id]?.quantity??0),0),[items,cart]);
  const area=delivery.areas.find(a=>a.id===areaId);const fee=fulfillment==='DELIVERY'?(area?.feeCents??0):0;const total=subtotal+fee;
  function change(id:string,delta:number){setCart(current=>{const quantity=Math.max(0,(current[id]?.quantity??0)+delta);return{...current,[id]:{quantity,note:current[id]?.note??''}}})}
  async function checkout(formData:FormData){setBusy(true);setError('');try{const lines=Object.entries(cart).filter(([,value])=>value.quantity>0).map(([itemId,value])=>({itemId,quantity:value.quantity,note:value.note}));const body={submissionKey,customerName:String(formData.get('name')??''),fulfillmentKind:fulfillment,deliveryAreaId:fulfillment==='DELIVERY'?areaId:null,address:fulfillment==='DELIVERY'?String(formData.get('address')??''):'',paymentMethod:String(formData.get('payment')??''),notes:String(formData.get('notes')??''),lines};const response=await fetch(`/api/public/delivery/${slug}/orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Não foi possível enviar o pedido');window.location.assign(result.whatsappUrl)}catch(cause){setError(cause instanceof Error?cause.message:'Erro ao enviar')}finally{setBusy(false)}}
  const orderable=subtotal>0&&subtotal>=delivery.minimumOrderCents&&(fulfillment==='PICKUP'||Boolean(areaId));
  return <div>{categories.map(category=><section key={category.id}><h2>{category.name}</h2>{category.items.filter(item=>item.available&&item.priceCents!=null).map(item=><article key={item.id} className="delivery-item"><div><strong>{item.title}</strong>{item.description&&<p>{item.description}</p>}<b>{brl(item.priceCents??0)}</b></div><div className="quantity"><button onClick={()=>change(item.id,-1)} type="button" aria-label={`Remover ${item.title}`}>−</button><span>{cart[item.id]?.quantity??0}</span><button onClick={()=>change(item.id,1)} type="button" aria-label={`Adicionar ${item.title}`}>+</button></div>{(cart[item.id]?.quantity??0)>0&&<input placeholder="Observação do item" value={cart[item.id]?.note??''} onChange={event=>setCart(current=>({...current,[item.id]:{quantity:current[item.id]?.quantity??1,note:event.target.value}}))}/>}</article>)}</section>)}<aside className="checkout-card"><div className="totals"><span>Subtotal <b>{brl(subtotal)}</b></span><span>Entrega <b>{brl(fee)}</b></span><span>Total <strong>{brl(total)}</strong></span></div>{delivery.minimumOrderCents>0&&subtotal<delivery.minimumOrderCents&&<p>Pedido mínimo: {brl(delivery.minimumOrderCents)}</p>}<form action={checkout} className="checkout-form"><input name="name" required minLength={2} placeholder="Seu nome"/><label>Como receber?<select value={fulfillment} onChange={e=>setFulfillment(e.target.value as 'PICKUP'|'DELIVERY')}><option value="DELIVERY">Entrega</option>{delivery.pickupEnabled&&<option value="PICKUP">Retirada no local</option>}</select></label>{fulfillment==='DELIVERY'&&<><select value={areaId} onChange={e=>setAreaId(e.target.value)} required><option value="">Selecione a área de entrega</option>{delivery.areas.map(option=><option key={option.id} value={option.id}>{option.name} — {brl(option.feeCents)}</option>)}</select><input name="address" required minLength={5} placeholder="Endereço completo"/></>}<select name="payment" required><option value="">Forma de pagamento</option>{delivery.paymentMethods.map(method=><option key={method} value={method}>{method}</option>)}</select><textarea name="notes" maxLength={2000} placeholder="Observações do pedido"/><button disabled={busy||!orderable}>{busy?'Enviando…':'Enviar pedido no WhatsApp'}</button>{error&&<p role="alert">{error}</p>}</form></aside></div>
}
